### PR TITLE
email

### PR DESCRIPTION
**Pull request by Niro007**
Hey it's me Niro007 from PD shoot an email here if you can. nirotcehatgmaildotcom

### CODE REVIEW

**Comment by phweda** [comment]
Sent.

**Comment by Niro007** [comment]
Can you see this message?

**Comment by Niro007** [comment]
Just trying to keep in contact with you, i just found out that you got
blocked at PD and it seemed strange to see that and i could not see any
other way to reach you.

**Comment by phweda** [comment]
Tried that email I must be missing something. Mine is phweda1@yahoo.com

**Comment by Niro007** [comment]
Hey there!

Was just going through my emails and saw yours... how's everything?

**Pull request closed without merging**
