### PR TITLE
[FIX] Fixed init settings when first run

### PR DESCRIPTION
**Pull request by dalonsogz**
[FIX] Fixed init settings when firdt run
- Fixed settings initiation when run at first time.
- Fixed loading of 'Output Data' field in settings panel.

### CODE REVIEW

**Comment by dalonsogz** [comment]
Just trying to fix the loading of settings when it is the frist run.

**Comment by phweda** [comment]
> Just trying to fix the loading of settings when it is the frist run.

I am looking at that too. But now am getting weird Gradle exception not allowing me to run from IDEA. FYI adding an empty settings file is not the way to go.

**Comment by phweda** [comment]
> > Just trying to fix the loading of settings when it is the frist run.
> 
> I am looking at that too. But now am getting weird Gradle exception not allowing me to run from IDEA. FYI adding an empty settings file is not the way to go.

Think is it a race condition.

**Comment by dalonsogz** [comment]
I commited the empty settings file by error because it was my first approach, but it's deleted in the second commit.

About 'settings' you can instantiate at first, so you don't have to care about to be null after. If you don't want to do that, you should control it in 'setObject' and 'getObject' at least, until I have tested, this work too. You can do more things too...

About, 'mfmSettings.isLoaded(true)' in 'SettingsPanel', I put it before the previous statement, to avoid a NullpointerExcepion. I think that should be ok.

I don't have the whole idea of the project but maybe these changes can help you.

**Comment by phweda** [comment]
> I commited the empty settings file by error because it was my first approach, but it's deleted in the second commit.
> 
> About 'settings' you can instantiate at first, so you don't have to care about to be null after. If you don't want to do that, you should control it in 'setObject' and 'getObject' at least, until I have tested, this work too. You can do more things too...
> 
> About, 'mfmSettings.isLoaded(true)' in 'SettingsPanel', I put it before the previous statement, to avoid a NullpointerExcepion. I think that should be ok.
> 
> I don't have the whole idea of the project but maybe these changes can help you.

Yes I think in getObject is best but need to test it out. Thanks for jumping in.

**Comment by dalonsogz** [comment]
> > > Just trying to fix the loading of settings when it is the frist run.
> > 
> > 
> > I am looking at that too. But now am getting weird Gradle exception not allowing me to run from IDEA. FYI adding an empty settings file is not the way to go.
> 
> Think is it a race condition.

This line '       
 ```
fullSetExtrasDirectories.putAll(MFMFileOps.findMAMEdirectories(Paths.get(getExtrasFullSetDir()),
                MFM_Constants.MAME_FOLDER_NAMES_ARRAY));'
```
From '`MFM.getMFMSettings().updateDirectoriesResourceFiles();`' in MFMSettings....
In method `updateDirectoriesResourceFiles' (MFMSettings)`, it is overwritten again `oursettings` to null. That's becuase it is initialized `MFMFileOps` that try to set `mfmsettings` with `MFMSettings.getInstance()`. In this moment `ourInstance.loaded` is false, then it try to do a `loadSettings()`, that put `ourSettings` to null() (`ourSettings = (HashMap<String, Object>) data.getObject(MFM_Constants.MFM_SETTINGS)`)  and then it returns ("NO SETTINGS FOUND") and levaing `ourSettings` with null.

So it causes a NullPointerException line 565 (`ourSettings.put(MFM_Constants.FULL_SET_DIRECTORIES_MAP, fullSetExtrasDirectories);`)

Also `updateDirectoriesResourceFiles` is called twice, I don't now why but it seems strange.

**Comment by phweda** [comment]
> > > > Just trying to fix the loading of settings when it is the frist run.
> > > 
> > > 
> > > I am looking at that too. But now am getting weird Gradle exception not allowing me to run from IDEA. FYI adding an empty settings file is not the way to go.
> > 
> > 
> > Think is it a race condition.
> 
> This line '
> 
> ```
> fullSetExtrasDirectories.putAll(MFMFileOps.findMAMEdirectories(Paths.get(getExtrasFullSetDir()),
>                MFM_Constants.MAME_FOLDER_NAMES_ARRAY));'
> ```
> 
> From '`MFM.getMFMSettings().updateDirectoriesResourceFiles();`' in MFMSettings....
> In method `updateDirectoriesResourceFiles' (MFMSettings)`, it is overwritten again `oursettings` to null. That's becuase it is initialized `MFMFileOps` that try to set `mfmsettings` with `MFMSettings.getInstance()`. In this moment `ourInstance.loaded` is false, then it try to do a `loadSettings()`, that put `ourSettings` to null() (`ourSettings = (HashMap<String, Object>) data.getObject(MFM_Constants.MFM_SETTINGS)`) and then it returns ("NO SETTINGS FOUND") and levaing `ourSettings` with null.
> 
> So it causes a NullPointerException line 565 (`ourSettings.put(MFM_Constants.FULL_SET_DIRECTORIES_MAP, fullSetExtrasDirectories);`)
> 
> Also `updateDirectoriesResourceFiles` is called twice, I don't now why but it seems strange.

Thanks for the insights. Was never

**Pull request merged**
